### ISSUE TITLE
원본 라이센스 관련 요청

### ISSUE THREAD

**Issue by Unengine** [deokseon/D-BMS#1]
안녕하세요, 4년 전에 제가 만들었던 UBMS에 많은 관심을 가져주시고 많은 부분을 활용해서 멋진 게임을 만들어주셔서 감사합니다.
오래 전에 작성한 코드라 항상 부끄럽지만 관련해서 프로젝트에 알맞게 수정해주신 부분을 보고 많이 노력해주셨다는게 느껴졌습니다.
UBMS는 현재는 사실상 버려둔 프로젝트지만 오픈소스로 공개하며 [AGPL-3.0](https://sktelecom.github.io/guide/use/obligation/agpl-3.0/) 라이센스를 적용해뒀던 상태입니다.
라이센스의 수정 의무에 따르면 AGPL-3.0 라이센스가 적용된 소프트웨어를 수정 후 재배포 시 저작권/라이센스 정보를 그대로 유지해서 재배포하셔야 합니다. 또한, 소스코드 수정 사항에 대한 고지를 포함하셔야 합니다.
그러나 여러모로 귀찮은 일이 되기에 라이센스를 [MIT 라이센스](https://sktelecom.github.io/guide/use/obligation/mit/)로 변경했으며, 저작권 고지 및 [라이센스 사본](https://github.com/Unengine/UBMS/blob/master/LICENSE)만 제공해주시면 됩니다.

**Comment by deokseon** [comment]
죄송합니다. 제가 먼저 잘 알아보고 했어야 하는 부분이었는데 오픈소스 이용이 처음이라 몰랐던 것을 알려주셔서 감사합니다.
라이센스는 바꿔 놓았습니다. 그리고 UBMS가 정말 많은 도움이 되었습니다. 감사합니다.

**Comment by Unengine** [comment]
라이센스 추가하신 커밋은 잘 봤는데, MIT 라이센스 사용하는 프로젝트가 MIT 라이센스가 될 필요는 없습니다.
다만 [저작권 고지/라이센스 사본 표기 예시(링크)](https://millo-l.github.io/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4-%EB%9D%BC%EC%9D%B4%EC%84%A0%EC%8A%A4-%EA%B3%A0%EC%A7%80-%EB%B0%A9%EB%B2%95/) 참고하셔서 제 작업물에 대한 라이센스 사본과 저작권 고지정도 부탁드립니다.

**Comment by deokseon** [comment]
수정했습니다. 번거롭게 해 드려서 죄송합니다.

**Comment by Unengine** [comment]
아닙니다! 이제 알게 되셨으니 문제 없죠 ㅎㅎ
확인했고 적절히 잘 들어간 것 같습니다. 오래된 프로젝트지만 관심 가져주셔서 정말 감사합니다!
